const messages = {
  en: {
    weekSubject: "{destination} is one week away", weekPreheader: "A concise readiness check for your {destination} trip.", readiness: "Trip readiness", onTrackIntro: "Your trip looks on track. Roamly has checked the travel details currently connected to this trip.", attentionIntro: "Roamly found a few items worth checking before you travel.", onTrack: "Everything important currently looks in order.", attentionList: "Here is what deserves your attention:", confirmed: "Confirmed", noBookings: "No confirmed bookings are attached yet.", needsAttention: "Needs attention", travelerNote: "Traveler note", bookingAttention: "needs attention", destination: "Destination", travelDates: "Travel dates", readinessLabel: "Readiness", looksOnTrack: "Looks on track", viewTrip: "View my trip", bookingEmailOffWeek: "Connect your booking email from the trip if you want Roamly to organize future confirmations.",
    tomorrowSubject: "{destination} starts tomorrow", tomorrowPreheader: "Your concise {destination} travel-day briefing.", tomorrowEyebrow: "Tomorrow with Roamly", tomorrowReady: "You are ready for tomorrow. Here is the short version of what Roamly knows.", tomorrowAttention: "There is one short list to check before you go.", tomorrowLine: "Tomorrow", transport: "Transport", stay: "Stay", firstUp: "First up", bookingEmailOn: "Booking email monitoring is connected.", bookingEmailOff: "Reconnect your booking email if you want Roamly to keep organizing confirmations.", companionTomorrow: "Live Companion is included for this trip and will guide you during travel.", departure: "Departure", tomorrowIntroReady: "Your trip is nearly here.", tomorrowIntroAttention: "A quick check before your trip begins.", viewTomorrow: "View tomorrow's plan",
    dailySubject: "Your day in {destination}", dailyPreheader: "A concise overview of today's plan in {destination}.", todayPlan: "Today's plan", dailyIntro: "A short overview for today.", todayOpen: "Today in {destination}: your schedule is open.", todayBusy: "Today in {destination}: here is what matters first.", later: "Later", confirmedTransport: "Confirmed", companionAvailable: "Live Companion is available for immediate travel guidance.", day: "Day", viewToday: "View today's plan",
    travelSubject: "{destination} starts today", travelPreheader: "A concise travel-day handoff for your {destination} trip.", travelDay: "Travel day", travelReady: "Your trip starts today. Here is the short version of what matters first.", around: "Today: your trip begins around {time}.", confirmedTransportFull: "Confirmed transport", companionTravel: "Live Companion is available for this trip and will guide you during travel.", today: "Today", openTrip: "Open my trip", quickCheck: "One quick check before you get moving.", tripHere: "Your trip is here."
  },
  fr: {
    weekSubject: "Votre voyage à {destination} commence dans une semaine", weekPreheader: "Un bref bilan de préparation pour votre voyage à {destination}.", readiness: "Préparation du voyage", onTrackIntro: "Votre voyage semble bien se dérouler. Roamly a vérifié les informations actuellement associées à ce voyage.", attentionIntro: "Roamly a repéré quelques éléments à vérifier avant votre départ.", onTrack: "Tout semble en ordre pour le moment.", attentionList: "Voici les éléments à vérifier :", confirmed: "Confirmé", noBookings: "Aucune réservation confirmée n’est encore associée.", needsAttention: "À vérifier", travelerNote: "Note du voyageur", bookingAttention: "nécessite votre attention", destination: "Destination", travelDates: "Dates du voyage", readinessLabel: "État", looksOnTrack: "Tout semble en ordre", viewTrip: "Voir mon voyage", bookingEmailOffWeek: "Connectez votre e-mail de réservation depuis le voyage pour que Roamly organise les confirmations à venir.",
    tomorrowSubject: "Votre voyage à {destination} commence demain", tomorrowPreheader: "Votre bref récapitulatif de voyage à {destination}.", tomorrowEyebrow: "Demain avec Roamly", tomorrowReady: "Vous êtes prêt pour demain. Voici l’essentiel des informations connues de Roamly.", tomorrowAttention: "Voici une courte liste à vérifier avant de partir.", tomorrowLine: "Demain", transport: "Transport", stay: "Hébergement", firstUp: "À venir en premier", bookingEmailOn: "Le suivi des e-mails de réservation est connecté.", bookingEmailOff: "Reconnectez votre e-mail de réservation pour que Roamly continue d’organiser vos confirmations.", companionTomorrow: "Live Companion est inclus pour ce voyage et vous guidera pendant vos déplacements.", departure: "Départ", tomorrowIntroReady: "Votre voyage approche.", tomorrowIntroAttention: "Une dernière vérification avant le début du voyage.", viewTomorrow: "Voir le programme de demain",
    dailySubject: "Votre journée à {destination}", dailyPreheader: "Un aperçu concis du programme du jour à {destination}.", todayPlan: "Programme du jour", dailyIntro: "Un bref aperçu de votre journée.", todayOpen: "Aujourd’hui à {destination} : votre programme est libre.", todayBusy: "Aujourd’hui à {destination} : voici les éléments importants en premier.", later: "Ensuite", confirmedTransport: "Confirmé", companionAvailable: "Live Companion est disponible pour vous guider pendant votre voyage.", day: "Jour", viewToday: "Voir le programme du jour",
    travelSubject: "Votre voyage à {destination} commence aujourd’hui", travelPreheader: "L’essentiel pour commencer votre voyage à {destination}.", travelDay: "Jour du départ", travelReady: "Votre voyage commence aujourd’hui. Voici l’essentiel à retenir.", around: "Aujourd’hui : votre voyage commence vers {time}.", confirmedTransportFull: "Transport confirmé", companionTravel: "Live Companion est disponible pour ce voyage et vous guidera pendant vos déplacements.", today: "Aujourd’hui", openTrip: "Ouvrir mon voyage", quickCheck: "Une dernière vérification avant de partir.", tripHere: "Votre voyage commence aujourd’hui."
  },
  es: {
    weekSubject: "Tu viaje a {destination} comienza en una semana", weekPreheader: "Un breve repaso para preparar tu viaje a {destination}.", readiness: "Preparación del viaje", onTrackIntro: "Tu viaje parece ir según lo previsto. Roamly ha revisado los detalles de viaje vinculados actualmente.", attentionIntro: "Roamly encontró algunos detalles que conviene revisar antes de viajar.", onTrack: "Por ahora, todo parece estar en orden.", attentionList: "Esto es lo que debes revisar:", confirmed: "Confirmado", noBookings: "Todavía no hay reservas confirmadas vinculadas.", needsAttention: "Requiere atención", travelerNote: "Nota del viajero", bookingAttention: "requiere atención", destination: "Destino", travelDates: "Fechas del viaje", readinessLabel: "Estado", looksOnTrack: "Todo parece estar en orden", viewTrip: "Ver mi viaje", bookingEmailOffWeek: "Conecta tu correo de reservas desde el viaje para que Roamly organice futuras confirmaciones.",
    tomorrowSubject: "Tu viaje a {destination} comienza mañana", tomorrowPreheader: "Un resumen breve de tu viaje a {destination}.", tomorrowEyebrow: "Mañana con Roamly", tomorrowReady: "Todo listo para mañana. Aquí tienes un resumen de lo que Roamly sabe.", tomorrowAttention: "Revisa esta breve lista antes de salir.", tomorrowLine: "Mañana", transport: "Transporte", stay: "Alojamiento", firstUp: "Primero", bookingEmailOn: "El seguimiento de correos de reservas está conectado.", bookingEmailOff: "Vuelve a conectar tu correo de reservas para que Roamly siga organizando las confirmaciones.", companionTomorrow: "Live Companion está incluido en este viaje y te guiará durante tus desplazamientos.", departure: "Salida", tomorrowIntroReady: "Tu viaje está muy cerca.", tomorrowIntroAttention: "Una última revisión antes de empezar el viaje.", viewTomorrow: "Ver el plan de mañana",
    dailySubject: "Tu día en {destination}", dailyPreheader: "Un resumen breve del plan de hoy en {destination}.", todayPlan: "Plan de hoy", dailyIntro: "Un breve resumen para hoy.", todayOpen: "Hoy en {destination}: tienes el día libre.", todayBusy: "Hoy en {destination}: esto es lo más importante.", later: "Más tarde", confirmedTransport: "Confirmado", companionAvailable: "Live Companion está disponible para orientarte durante el viaje.", day: "Día", viewToday: "Ver el plan de hoy",
    travelSubject: "Tu viaje a {destination} comienza hoy", travelPreheader: "Lo esencial para empezar tu viaje a {destination}.", travelDay: "Día de viaje", travelReady: "Tu viaje comienza hoy. Aquí tienes lo más importante.", around: "Hoy: tu viaje comienza aproximadamente a las {time}.", confirmedTransportFull: "Transporte confirmado", companionTravel: "Live Companion está disponible para este viaje y te guiará durante tus desplazamientos.", today: "Hoy", openTrip: "Abrir mi viaje", quickCheck: "Una última revisión antes de salir.", tripHere: "Tu viaje ya está aquí."
  },
  ja: {
    weekSubject: "{destination}への旅行まであと1週間です", weekPreheader: "{destination}への旅行準備を簡潔に確認しましょう。", readiness: "旅行の準備状況", onTrackIntro: "旅行は順調に進んでいるようです。Roamlyが現在登録されている旅行情報を確認しました。", attentionIntro: "出発前に確認しておきたい項目があります。", onTrack: "現在、重要な項目は整っています。", attentionList: "次の項目をご確認ください：", confirmed: "確定済み", noBookings: "確定済みの予約はまだ登録されていません。", needsAttention: "要確認", travelerNote: "旅行者メモ", bookingAttention: "確認が必要です", destination: "目的地", travelDates: "旅行日程", readinessLabel: "状況", looksOnTrack: "順調です", viewTrip: "旅行を見る", bookingEmailOffWeek: "Roamlyが今後の確認メールを整理できるよう、旅行画面から予約用メールを接続してください。",
    tomorrowSubject: "{destination}への旅行は明日始まります", tomorrowPreheader: "{destination}への旅行前に確認したい要点です。", tomorrowEyebrow: "Roamlyと過ごす明日", tomorrowReady: "明日の準備は整っています。Roamlyが把握している内容を簡潔にまとめました。", tomorrowAttention: "出発前に次の項目を確認してください。", tomorrowLine: "明日", transport: "交通", stay: "宿泊先", firstUp: "最初の予定", bookingEmailOn: "予約メールの確認が接続されています。", bookingEmailOff: "予約確認メールの整理を続けるには、予約用メールを再接続してください。", companionTomorrow: "この旅行ではLive Companionをご利用いただけます。旅行中の案内を行います。", departure: "出発", tomorrowIntroReady: "旅行が近づいています。", tomorrowIntroAttention: "旅行開始前の簡単な確認です。", viewTomorrow: "明日の予定を見る",
    dailySubject: "{destination}で過ごす今日", dailyPreheader: "{destination}での今日の予定を簡潔にご案内します。", todayPlan: "今日の予定", dailyIntro: "今日の予定を簡潔にご案内します。", todayOpen: "{destination}での今日は、予定に余裕があります。", todayBusy: "{destination}での今日、まず確認したいことはこちらです。", later: "その後", confirmedTransport: "確定済み", companionAvailable: "Live Companionが旅行中の案内をお手伝いします。", day: "日目", viewToday: "今日の予定を見る",
    travelSubject: "{destination}への旅行は今日始まります", travelPreheader: "{destination}への旅行初日に役立つ要点です。", travelDay: "旅行初日", travelReady: "旅行が今日始まります。まず確認したい要点をまとめました。", around: "今日の旅行開始予定時刻：{time}。", confirmedTransportFull: "確定済みの交通予約", companionTravel: "この旅行ではLive Companionが利用でき、旅行中の案内を行います。", today: "今日", openTrip: "旅行を開く", quickCheck: "出発前の簡単な確認です。", tripHere: "いよいよ旅行当日です。"
  },
  ko: {
    weekSubject: "{destination} 여행이 일주일 남았습니다", weekPreheader: "{destination} 여행 준비 상태를 간단히 확인해 보세요.", readiness: "여행 준비 상태", onTrackIntro: "여행이 순조롭게 진행 중인 것 같습니다. Roamly가 현재 연결된 여행 정보를 확인했습니다.", attentionIntro: "여행 전에 확인해야 할 항목이 있습니다.", onTrack: "현재 중요한 내용은 모두 문제없어 보입니다.", attentionList: "다음 항목을 확인해 주세요:", confirmed: "확정됨", noBookings: "아직 확정된 예약이 연결되어 있지 않습니다.", needsAttention: "확인 필요", travelerNote: "여행자 메모", bookingAttention: "확인이 필요합니다", destination: "목적지", travelDates: "여행 날짜", readinessLabel: "준비 상태", looksOnTrack: "순조로워요", viewTrip: "내 여행 보기", bookingEmailOffWeek: "Roamly가 향후 확인 메일을 정리할 수 있도록 여행에서 예약 이메일을 연결해 주세요.",
    tomorrowSubject: "{destination} 여행이 내일 시작됩니다", tomorrowPreheader: "{destination} 여행 전 간단한 안내입니다.", tomorrowEyebrow: "Roamly와 함께하는 내일", tomorrowReady: "내일 여행 준비가 되었습니다. Roamly가 확인한 내용을 간단히 정리했어요.", tomorrowAttention: "출발 전에 다음 항목을 확인해 주세요.", tomorrowLine: "내일", transport: "교통", stay: "숙소", firstUp: "첫 일정", bookingEmailOn: "예약 이메일 모니터링이 연결되어 있습니다.", bookingEmailOff: "예약 확인을 계속 정리하려면 예약 이메일을 다시 연결해 주세요.", companionTomorrow: "이 여행에는 Live Companion이 포함되어 여행 중 안내를 제공합니다.", departure: "출발", tomorrowIntroReady: "여행이 얼마 남지 않았어요.", tomorrowIntroAttention: "여행 시작 전 간단히 확인해 주세요.", viewTomorrow: "내일 일정 보기",
    dailySubject: "오늘의 {destination} 여행", dailyPreheader: "오늘 {destination} 일정을 간단히 안내합니다.", todayPlan: "오늘의 일정", dailyIntro: "오늘 일정을 간단히 정리했어요.", todayOpen: "오늘 {destination}에서는 여유롭게 일정을 즐길 수 있어요.", todayBusy: "오늘 {destination}에서 먼저 확인할 내용을 알려드려요.", later: "이후 일정", confirmedTransport: "확정됨", companionAvailable: "Live Companion이 여행 중 필요한 안내를 제공합니다.", day: "일차", viewToday: "오늘 일정 보기",
    travelSubject: "{destination} 여행이 오늘 시작됩니다", travelPreheader: "{destination} 여행 첫날에 필요한 핵심 정보입니다.", travelDay: "여행 첫날", travelReady: "오늘 여행이 시작됩니다. 먼저 확인할 내용을 간단히 정리했어요.", around: "오늘 여행은 {time}쯤 시작됩니다.", confirmedTransportFull: "확정된 교통편", companionTravel: "이 여행에서 Live Companion이 여행 중 안내를 제공합니다.", today: "오늘", openTrip: "내 여행 열기", quickCheck: "출발 전 간단히 확인해 주세요.", tripHere: "여행이 시작되는 날이에요."
  },
  zh: {
    weekSubject: "距离前往{destination}还有一周", weekPreheader: "快速查看前往{destination}的行前准备情况。", readiness: "行程准备情况", onTrackIntro: "行程目前看起来进展顺利。Roamly已检查此行程中现有的旅行信息。", attentionIntro: "出发前有几项内容值得确认。", onTrack: "目前重要事项看起来都已就绪。", attentionList: "请留意以下事项：", confirmed: "已确认", noBookings: "目前还没有关联已确认的预订。", needsAttention: "需要留意", travelerNote: "旅客备注", bookingAttention: "需要留意", destination: "目的地", travelDates: "旅行日期", readinessLabel: "准备情况", looksOnTrack: "进展顺利", viewTrip: "查看我的行程", bookingEmailOffWeek: "请从行程中连接预订邮箱，以便Roamly整理后续确认邮件。",
    tomorrowSubject: "前往{destination}的行程明天开始", tomorrowPreheader: "前往{destination}出发前的简要提示。", tomorrowEyebrow: "Roamly陪伴你的明天", tomorrowReady: "明天就要出发了。以下是Roamly掌握的信息摘要。", tomorrowAttention: "出发前请快速检查以下事项。", tomorrowLine: "明天", transport: "交通", stay: "住宿", firstUp: "首先安排", bookingEmailOn: "预订邮件监控已连接。", bookingEmailOff: "重新连接预订邮箱，Roamly即可继续整理确认邮件。", companionTomorrow: "此行程已包含Live Companion，可在旅途中为你提供指引。", departure: "出发", tomorrowIntroReady: "旅程即将开始。", tomorrowIntroAttention: "行程开始前的快速检查。", viewTomorrow: "查看明日计划",
    dailySubject: "你在{destination}的一天", dailyPreheader: "简要查看今天在{destination}的安排。", todayPlan: "今日计划", dailyIntro: "今天的简要安排。", todayOpen: "今天在{destination}：日程比较宽松。", todayBusy: "今天在{destination}：先看看这些重要事项。", later: "稍后", confirmedTransport: "已确认", companionAvailable: "Live Companion可提供即时旅行指引。", day: "日", viewToday: "查看今日计划",
    travelSubject: "前往{destination}的行程今天开始", travelPreheader: "开启{destination}旅程前需要了解的重点。", travelDay: "出行日", travelReady: "今天就要出发了。以下是最重要的信息摘要。", around: "今天的行程预计于{time}左右开始。", confirmedTransportFull: "已确认交通", companionTravel: "此行程可使用Live Companion，旅途中将为你提供指引。", today: "今天", openTrip: "打开我的行程", quickCheck: "出发前快速检查一下。", tripHere: "旅程即将开启。"
  }
};

export function briefingMessage(locale, key, values = {}) {
  let message = messages[locale][key] || messages.en[key] || key;
  for (const [name, value] of Object.entries(values)) message = message.replaceAll(`{${name}}`, value);
  return message;
}

const activityNotificationCopy = {
  en: {
    nearbyTitle: "You're nearby: {activity}", nearbyBody: "You're close to your next planned activity. Open Roamly when you're ready.",
    soonTitle: "Starting soon: {activity}", soonBody: "📍 {location} · starts in {minutes} min. Tap to open directions.", nowTitle: "Now: {activity}", nowBody: "Your scheduled activity starts now.", soonGeneric: "Starting soon. Tap to open directions."
  },
  fr: {
    nearbyTitle: "À proximité : {activity}", nearbyBody: "Vous êtes près de votre prochaine activité. Ouvrez Roamly lorsque vous êtes prêt.",
    soonTitle: "Bientôt : {activity}", soonBody: "📍 {location} · commence dans {minutes} min. Touchez pour ouvrir l’itinéraire.", nowTitle: "Maintenant : {activity}", nowBody: "Votre activité prévue commence maintenant.", soonGeneric: "Le départ est imminent. Touchez pour ouvrir l’itinéraire."
  },
  es: {
    nearbyTitle: "Estás cerca: {activity}", nearbyBody: "Estás cerca de tu próxima actividad. Abre Roamly cuando quieras.",
    soonTitle: "Empieza pronto: {activity}", soonBody: "📍 {location} · empieza en {minutes} min. Toca para ver cómo llegar.", nowTitle: "Ahora: {activity}", nowBody: "Tu actividad programada empieza ahora.", soonGeneric: "Empieza pronto. Toca para ver cómo llegar."
  },
  ja: {
    nearbyTitle: "近くにいます：{activity}", nearbyBody: "次の予定場所の近くです。準備ができたらRoamlyを開いてください。",
    soonTitle: "まもなく開始：{activity}", soonBody: "📍 {location} · あと{minutes}分で開始します。タップして経路を表示。", nowTitle: "開始時間です：{activity}", nowBody: "予定していたアクティビティが始まります。", soonGeneric: "まもなく開始します。タップして経路を表示。"
  },
  ko: {
    nearbyTitle: "근처에 있어요: {activity}", nearbyBody: "다음 일정 장소 근처에 도착했어요. 준비되면 Roamly를 여세요.",
    soonTitle: "곧 시작해요: {activity}", soonBody: "📍 {location} · {minutes}분 후 시작합니다. 탭하여 길찾기를 여세요.", nowTitle: "지금 시작해요: {activity}", nowBody: "예정된 일정이 지금 시작됩니다.", soonGeneric: "곧 시작합니다. 탭하여 길찾기를 여세요."
  },
  zh: {
    nearbyTitle: "你已抵达附近：{activity}", nearbyBody: "你已接近下一个计划活动。准备好后打开Roamly。",
    soonTitle: "即将开始：{activity}", soonBody: "📍 {location} · {minutes}分钟后开始。轻触查看路线。", nowTitle: "现在开始：{activity}", nowBody: "你安排的活动现在开始。", soonGeneric: "即将开始。轻触查看路线。"
  }
};

export function localizeActivityNotification(locale, type, title, body, metadata = {}) {
  if (locale === "en" || !activityNotificationCopy[locale]) return { title, body };
  const copy = activityNotificationCopy[locale];
  const activity = type === "nearby_activity"
    ? title.replace(/^(You're nearby: |You’re nearby: )/i, "")
    : type === "next_activity"
      ? title.replace(/^Starting soon: /i, "")
      : title.replace(/^Now: /i, "");
  if (type === "nearby_activity" && /^(You're nearby: |You’re nearby: )/i.test(title)) return { title: copy.nearbyTitle.replace("{activity}", activity), body: copy.nearbyBody };
  if (type === "next_activity" && /^Starting soon: /i.test(title)) {
    const location = typeof metadata.locationLabel === "string" && metadata.locationLabel.trim() ? metadata.locationLabel.trim() : "";
    const minutes = Number.isFinite(Number(metadata.countdownMinutes)) ? String(metadata.countdownMinutes) : "";
    return { title: copy.soonTitle.replace("{activity}", activity), body: location && minutes ? copy.soonBody.replace("{location}", location).replace("{minutes}", minutes) : copy.soonGeneric };
  }
  if (type === "activity_start" && /^Now: /i.test(title)) return { title: copy.nowTitle.replace("{activity}", activity), body: copy.nowBody };
  return { title, body };
}
