import type { HotelCandidate as BaseHotelCandidate } from "@/lib/roamly/candidateDecisionCore";
import type { HotelConstraints, TripPlannerPayload } from "@/lib/trip-planner";

type HotelCandidate = BaseHotelCandidate & { providerProductId?: string | null };

export type HotelInventoryState = "OK" | "PROVIDER_NOT_CONFIGURED" | "TIMEOUT" | "RATE_LIMITED" | "NO_RESULTS" | "EXACT_PROPERTY_NOT_FOUND" | "EXACT_PROPERTY_AMBIGUOUS" | "NO_AVAILABLE_RATE" | "MALFORMED_PROVIDER_RESPONSE" | "STALE_RATE" | "CURRENCY_MISMATCH";
export type HotelInventorySearchInput = {
  destination?: string | null; latitude?: number | null; longitude?: number | null; checkIn: string; checkOut: string; travelers: number; rooms: number; children?: number; childAges?: number[]; currency: string; providerLocationId?: number | null; providerLocationType?: "city" | "district" | "region" | "airport" | "landmark" | "hotel" | null; bookerCountry?: string | null; exactPropertyRequest?: string | null; neighborhood?: string | null; constraints?: HotelConstraints;
};
export type HotelPropertyMatch = { status: "EXACT" | "STRONG_MATCH" | "AMBIGUOUS" | "NOT_FOUND"; providerPropertyId: string | null; canonicalName: string | null; confidence: number; candidates: Array<{ providerPropertyId: string; name: string; address: string | null }> };
export type HotelLocationMatch = { status: "EXACT" | "STRONG_MATCH" | "AMBIGUOUS" | "NOT_FOUND"; providerLocationId: number | null; providerLocationType: "city" | "district" | "region" | "airport" | "landmark" | "hotel" | null; canonicalName: string | null; coordinates: { latitude: number; longitude: number } | null; confidence: number; source: "booking_autocomplete" };
export type HotelInventoryResult = { state: HotelInventoryState; provider: "booking_demand"; candidates: HotelCandidate[]; searchedAt: string; expiresAt: string; warning?: string };
export type HotelInventoryProvider = { searchHotels(input: HotelInventorySearchInput): Promise<HotelInventoryResult>; resolveLocation(input: { query: string; country: string }): Promise<HotelLocationMatch>; resolveProperty(input: HotelInventorySearchInput): Promise<HotelPropertyMatch>; getPropertyAvailability(input: HotelInventorySearchInput & { providerPropertyId: string }): Promise<HotelInventoryResult>; getRates(input: HotelInventorySearchInput & { providerPropertyId: string }): Promise<HotelInventoryResult> };

type FetchLike = typeof fetch;
type Charge = { amount?: number | string | null; currency?: string | null; included?: boolean | null; chargeable_online?: boolean | null; type?: string | null };
type BookingProduct = { id: string | number; room?: string | { name?: string | null; description?: string | null; amenities?: string[] } | null; price?: { total?: number | string | null; display?: number | string | null; charges?: Charge[] | null } | null; number_available_at_this_price?: number | null; inventory?: { type?: string | null; number?: number | null } | null; policies?: { cancellation?: Record<string, unknown> | null; payment?: Record<string, unknown> | null } | null; url?: string | { app?: string | null; web?: string | null } | null };
type BookingProperty = { id: string; name?: string | null; address?: string | null; coordinates?: { latitude?: number; longitude?: number } | null; neighborhood?: string | null; stars?: number | null; amenities?: string[]; products?: BookingProduct[]; url?: string | { app?: string | null; web?: string | null } | null; deepLinkUrl?: string | { app?: string | null; web?: string | null } | null; currency?: string | { accommodation?: string; booker?: string } | null };

function text(value: unknown) { return typeof value === "string" || typeof value === "number" ? String(value).trim() : ""; }
function num(value: unknown) { const n = typeof value === "number" ? value : typeof value === "string" && value.trim() ? Number(value) : NaN; return Number.isFinite(n) ? n : null; }
function enabled() { return text(process.env.ROAMLY_HOTEL_INVENTORY_PROVIDER).toLowerCase() === "booking" && Boolean(text(process.env.BOOKING_DEMAND_API_TOKEN) && text(process.env.BOOKING_DEMAND_AFFILIATE_ID)); }
export function hotelInventoryConfigured() { return enabled(); }
function now() { return new Date(); }
function expiry(d: Date) { const configured = num(process.env.ROAMLY_HOTEL_RATE_TTL_MINUTES); const minutes = configured && configured > 0 ? Math.min(configured, 60) : 15; return new Date(d.getTime() + minutes * 60_000).toISOString(); }
function nights(a: string, b: string) { const n = Math.ceil((Date.parse(b) - Date.parse(a)) / 86_400_000); return n > 0 ? n : null; }
function normalized(value: string) { return value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, " ").trim(); }

export function hotelInventoryInputFromPayload(payload: TripPlannerPayload): HotelInventorySearchInput {
  const constraints = payload.constraints?.hotel;
  const travelerDetails = payload.travelers as (typeof payload.travelers & { childAges?: number[] }) | undefined;
  return { destination: payload.destinationCity || payload.destination, latitude: payload.destinationLatitude ?? payload.destinationPlace?.latitude ?? null, longitude: payload.destinationLongitude ?? payload.destinationPlace?.longitude ?? null, checkIn: payload.startDate, checkOut: payload.endDate, travelers: payload.travelersCount || payload.travelers?.adults || 1, rooms: payload.rooms || 1, children: payload.travelers?.children || 0, childAges: travelerDetails?.childAges || [], currency: (payload.budgetCurrency || "CAD").toUpperCase(), providerLocationId: null, providerLocationType: null, bookerCountry: text(process.env.BOOKING_DEMAND_BOOKER_COUNTRY).toLowerCase() || null, exactPropertyRequest: constraints?.exactPropertyRequest?.value || null, neighborhood: constraints?.requiredNeighborhood?.value || constraints?.preferredNeighborhood || null, constraints };
}

function bookingUrl(value: unknown) { if (typeof value === "string") return value.trim() || null; if (value && typeof value === "object") { const row = value as Record<string, unknown>; return text(row.web) || text(row.app) || null; } return null; }
function currency(value: unknown, fallback?: unknown) { if (typeof value === "string") return value.toUpperCase(); if (value && typeof value === "object") return text((value as Record<string, unknown>).accommodation || (value as Record<string, unknown>).booker).toUpperCase(); return text(fallback).toUpperCase(); }
function roomText(room: BookingProduct["room"]) { return typeof room === "object" && room ? text(room.description) || text(room.name) || null : null; }
function roomAmenities(room: BookingProduct["room"]) { return typeof room === "object" && room ? (room.amenities || []).filter((x): x is string => typeof x === "string") : []; }

function requestBody(input: HotelInventorySearchInput, propertyIds?: string[], availability = false) {
  const guests: Record<string, unknown> = { number_of_adults: input.travelers, number_of_rooms: input.rooms }; if (input.childAges?.length) guests.children = input.childAges;
  const locationKey = input.providerLocationType || "city";
  return { booker: { country: input.bookerCountry, platform: "desktop" }, checkin: input.checkIn, checkout: input.checkOut, currency: input.currency, guests, extras: ["products", "extra_charges"], ...(propertyIds?.length ? { [availability ? "accommodation" : "accommodations"]: availability ? Number(propertyIds[0]) : propertyIds.map(Number) } : {}), ...(input.providerLocationId && ["city", "district", "region", "airport", "landmark"].includes(locationKey) ? { [locationKey]: input.providerLocationId } : {}) };
}

function propertyRows(payload: unknown): { rows: BookingProperty[]; currency?: string } | null {
  if (!payload || typeof payload !== "object") return null;
  const root = payload as Record<string, unknown>;
  const data = Array.isArray(root.data) ? root.data : root.data && typeof root.data === "object" ? [root.data] : null;
  if (!data) return null;
  const rows: BookingProperty[] = [];
  for (const item of data) {
    if (!item || typeof item !== "object") return null;
    const row = item as Record<string, unknown>;
    const id = text(row.id);
    if (!id) return null;
    const location = row.location && typeof row.location === "object" ? row.location as Record<string, unknown> : {};
    const addressValue = row.address ?? location.address;
    const address = typeof addressValue === "object" && addressValue ? text(Object.values(addressValue as Record<string, unknown>)[0]) : text(addressValue);
    const coordinateValue = row.coordinates ?? location.coordinates;
    const coordinates = coordinateValue && typeof coordinateValue === "object" ? coordinateValue as Record<string, unknown> : null;
    const rating = row.rating && typeof row.rating === "object" ? row.rating as Record<string, unknown> : {};
    const nameValue = row.name;
    const name = typeof nameValue === "object" && nameValue ? text(Object.values(nameValue as Record<string, unknown>)[0]) : text(nameValue);
    rows.push({ id, name: name || null, address: address || null, coordinates: coordinates ? { latitude: num(coordinates.latitude) ?? undefined, longitude: num(coordinates.longitude) ?? undefined } : null, neighborhood: text(row.neighborhood) || null, stars: num(row.stars) ?? num(rating.stars), amenities: Array.isArray(row.amenities) ? row.amenities.filter((x): x is string => typeof x === "string") : [], products: Array.isArray(row.products) ? row.products.filter((x): x is BookingProduct => Boolean(x && typeof x === "object" && text((x as Record<string, unknown>).id))) : [], url: row.url as BookingProperty["url"], deepLinkUrl: row.deep_link_url as BookingProperty["deepLinkUrl"], currency: row.currency as BookingProperty["currency"] });
  }
  return { rows, currency: currency(root.currency) || undefined };
}

export function resolveBookingLocationMatch(query: string, suggestions: Array<{ id: number; type: HotelLocationMatch["providerLocationType"]; name: string; latitude?: number; longitude?: number }>): HotelLocationMatch { const wanted = normalized(query); const matches = suggestions.filter(x => normalized(x.name) === wanted || normalized(x.name).includes(wanted)); if (!matches.length) return { status: "NOT_FOUND", providerLocationId: null, providerLocationType: null, canonicalName: null, coordinates: null, confidence: 0, source: "booking_autocomplete" }; if (matches.length > 1) return { status: "AMBIGUOUS", providerLocationId: null, providerLocationType: null, canonicalName: null, coordinates: null, confidence: 0, source: "booking_autocomplete" }; const x = matches[0]; const exact = normalized(x.name) === wanted; return { status: exact ? "EXACT" : "STRONG_MATCH", providerLocationId: x.id, providerLocationType: x.type, canonicalName: x.name, coordinates: x.latitude != null && x.longitude != null ? { latitude: x.latitude, longitude: x.longitude } : null, confidence: exact ? 1 : .85, source: "booking_autocomplete" }; }
export function normalizeBookingLocationResponse(payload: unknown, query: string): HotelLocationMatch { const root = payload && typeof payload === "object" ? payload as Record<string, unknown> : {}; const data = Array.isArray(root.data) ? root.data : []; const suggestions = data.flatMap(item => { if (!item || typeof item !== "object") return []; const row = item as Record<string, unknown>; const id = num(row.id); const type = text(row.type) as HotelLocationMatch["providerLocationType"]; const name = typeof row.name === "object" && row.name ? text(Object.values(row.name as Record<string, unknown>)[0]) : text(row.name); const loc = row.location && typeof row.location === "object" ? row.location as Record<string, unknown> : {}; const c = loc.coordinates && typeof loc.coordinates === "object" ? loc.coordinates as Record<string, unknown> : {}; return id != null && name && type ? [{ id, type, name, latitude: num(c.latitude) ?? undefined, longitude: num(c.longitude) ?? undefined }] : []; }); return resolveBookingLocationMatch(query, suggestions); }
export function resolveBookingPropertyMatch(query: string, properties: Array<{ id: string; name?: string | null; address?: string | null }>): HotelPropertyMatch { const wanted = normalized(query); const usable = properties.filter(x => x.name); const exact = usable.filter(x => normalized(x.name as string) === wanted); const list = (xs: typeof usable) => xs.map(x => ({ providerPropertyId: x.id, name: x.name as string, address: x.address || null })); if (exact.length === 1) return { status: "EXACT", providerPropertyId: exact[0].id, canonicalName: exact[0].name as string, confidence: 1, candidates: list(exact) }; if (exact.length > 1) return { status: "AMBIGUOUS", providerPropertyId: null, canonicalName: null, confidence: 0, candidates: list(exact) }; const strong = usable.filter(x => normalized(x.name as string).includes(wanted) || wanted.includes(normalized(x.name as string))); if (strong.length === 1) return { status: "STRONG_MATCH", providerPropertyId: strong[0].id, canonicalName: strong[0].name as string, confidence: .85, candidates: list(strong) }; if (strong.length > 1) return { status: "AMBIGUOUS", providerPropertyId: null, canonicalName: null, confidence: 0, candidates: list(strong) }; return { status: "NOT_FOUND", providerPropertyId: null, canonicalName: null, confidence: 0, candidates: [] }; }

function chargeTotal(charges: Charge[] | null | undefined) { const values = (charges || []).map(x => num(x.amount)).filter((x): x is number => x != null); return values.length === (charges || []).length && values.length ? values.reduce((a, b) => a + b, 0) : null; }
function inclusion(charges: Charge[] | null | undefined) { if (!charges?.length) return "unknown" as const; if (charges.every(x => x.included === true)) return "included" as const; if (charges.every(x => x.included === false)) return "excluded" as const; return "unknown" as const; }
function cancellationText(policy: Record<string, unknown> | null | undefined) { if (!policy) return null; const type = text(policy.type).toLowerCase(); return type.includes("non") ? "non-refundable" : type.includes("free") || policy.free_cancellation_until ? "refundable/conditional" : type || "conditional/unknown"; }
function candidateFromBooking(property: BookingProperty, product: BookingProduct | undefined, input: HotelInventorySearchInput, searchedAt: string, expires: string, responseCurrency?: string): HotelCandidate | null { if (!product?.id || !property.name) return null; const price = product.price; const total = num(price?.total); const charges = price?.charges || []; const available = product.number_available_at_this_price != null ? product.number_available_at_this_price > 0 : text(product.inventory?.type).toLowerCase() === "available"; const n = nights(input.checkIn, input.checkOut); const cur = currency(property.currency, responseCurrency || input.currency); return { candidateId: `booking:${property.id}:${product.id}`, category: "hotel", source: "Booking.com Demand API", sourceType: "provider_api", searchedAt, factualStatus: "verified", bookingStatus: "bookable", deepLink: bookingUrl(product.url) || bookingUrl(property.deepLinkUrl) || bookingUrl(property.url), providerPropertyId: property.id, providerProductId: text(product.id), name: property.name, address: property.address || null, coordinates: property.coordinates?.latitude != null && property.coordinates?.longitude != null ? { latitude: property.coordinates.latitude, longitude: property.coordinates.longitude } : null, neighborhood: property.neighborhood || null, quality: property.stars ?? null, checkIn: input.checkIn, checkOut: input.checkOut, roomDescription: roomText(product.room), occupancy: { travelers: input.travelers, rooms: input.rooms, childAges: input.childAges || [] }, amenities: [...(property.amenities || []), ...roomAmenities(product.room)], pricePerNight: total != null && n ? total / n : null, totalStayPrice: total, taxesFees: chargeTotal(charges), taxInclusionStatus: inclusion(charges), feeInclusionStatus: inclusion(charges), currency: cur || input.currency, availabilityStatus: available ? "available" : "unknown", cancellationPolicy: cancellationText(product.policies?.cancellation), expiresAt: expires }; }
export function normalizeBookingAccommodationResponse(payload: unknown, input: HotelInventorySearchInput, searchedAt: string, expires: string): HotelCandidate[] | null { const parsed = propertyRows(payload); if (!parsed) return null; return parsed.rows.flatMap(p => { const c = candidateFromBooking(p, p.products?.[0], input, searchedAt, expires, parsed.currency); return c ? [c] : []; }); }
function mergePropertyDetails(searchPayload: unknown, detailsPayload: unknown): unknown {
  const search = propertyRows(searchPayload); const details = propertyRows(detailsPayload); if (!search || !details) return searchPayload;
  const byId = new Map(details.rows.map(row => [row.id, row]));
  return { data: search.rows.map(row => { const detail = byId.get(row.id); if (!detail) return row; return { ...detail, ...row, name: row.name || detail.name, address: row.address || detail.address, coordinates: row.coordinates || detail.coordinates, neighborhood: row.neighborhood || detail.neighborhood, stars: row.stars ?? detail.stars, amenities: row.amenities?.length ? row.amenities : detail.amenities, products: row.products?.length ? row.products : detail.products, url: row.url || detail.url, deep_link_url: row.deepLinkUrl || detail.deepLinkUrl, currency: row.currency || detail.currency }; }) };
}
function unavailable(state: HotelInventoryState, warning: string): HotelInventoryResult { const d = now(); return { state, provider: "booking_demand", candidates: [], searchedAt: d.toISOString(), expiresAt: expiry(d), warning }; }

export function createBookingDemandProvider(fetchImpl: FetchLike = fetch): HotelInventoryProvider {
  async function raw(path: string, body: Record<string, unknown>) { if (!enabled()) return { state: "PROVIDER_NOT_CONFIGURED" as HotelInventoryState, warning: "Booking.com Demand API is not configured." }; const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), num(process.env.ROAMLY_HOTEL_INVENTORY_TIMEOUT_MS) || 8000); try { const res = await fetchImpl(`https://demandapi.booking.com/3.2${path}`, { method: "POST", headers: { Authorization: `Bearer ${text(process.env.BOOKING_DEMAND_API_TOKEN)}`, "X-Affiliate-Id": text(process.env.BOOKING_DEMAND_AFFILIATE_ID), "Content-Type": "application/json" }, body: JSON.stringify(body), signal: controller.signal }); if (res.status === 401 || res.status === 403) return { state: "PROVIDER_NOT_CONFIGURED" as HotelInventoryState, warning: "Booking.com Demand API credentials are not authorized." }; if (res.status === 429) return { state: "RATE_LIMITED" as HotelInventoryState, warning: "Booking.com Demand API rate limit reached." }; if (!res.ok) return { state: "NO_RESULTS" as HotelInventoryState, warning: `Booking.com Demand API returned HTTP ${res.status}.` }; try { return { state: "OK" as HotelInventoryState, payload: await res.json() }; } catch { return { state: "MALFORMED_PROVIDER_RESPONSE" as HotelInventoryState, warning: "Booking.com Demand API returned malformed JSON." }; } } catch (e) { return { state: e instanceof Error && e.name === "AbortError" ? "TIMEOUT" as const : "NO_RESULTS" as const, warning: "Booking.com Demand API request failed." }; } finally { clearTimeout(timer); } }
  async function search(input: HotelInventorySearchInput, ids?: string[], availability = false): Promise<HotelInventoryResult> { if (!input.bookerCountry) return unavailable("PROVIDER_NOT_CONFIGURED", "Booking.com booker country is not configured."); if (!ids?.length && !input.providerLocationId) return unavailable("NO_RESULTS", "Booking.com location ID is required for hotel search."); if (ids?.some(id => !Number.isInteger(Number(id)) || Number(id) <= 0)) return unavailable("MALFORMED_PROVIDER_RESPONSE", "Booking.com property identifiers must be numeric."); const d = now(); const result = await raw(availability ? "/accommodations/availability" : "/accommodations/search", requestBody(input, ids, availability)); if (result.state !== "OK") return unavailable(result.state, result.warning || "Booking.com hotel search failed."); let payload = result.payload; const parsed = propertyRows(payload); if (!parsed) return unavailable("MALFORMED_PROVIDER_RESPONSE", "Booking.com response did not contain supported accommodation data."); const missingIds = parsed.rows.filter(row => !row.name).map(row => row.id).slice(0, 20); if (missingIds.length) { const details = await raw("/accommodations/details", { accommodations: missingIds.map(Number), extras: ["description", "facilities", "policies", "rooms"] }); if (details.state === "OK") payload = mergePropertyDetails(payload, details.payload); } const candidates = normalizeBookingAccommodationResponse(payload, input, d.toISOString(), expiry(d)); if (!candidates) return unavailable("MALFORMED_PROVIDER_RESPONSE", "Booking.com response did not contain supported accommodation data."); if (!candidates.length) return unavailable("NO_AVAILABLE_RATE", "Booking.com returned no named products with rates."); return { state: "OK", provider: "booking_demand", candidates, searchedAt: d.toISOString(), expiresAt: expiry(d) }; }
  return { async resolveLocation({ query, country }) { const result = await raw("/common/autocomplete", { query, country: country.toLowerCase(), filters: { types: ["city", "district", "region", "airport", "landmark"] } }); if (result.state !== "OK") return { status: "NOT_FOUND", providerLocationId: null, providerLocationType: null, canonicalName: null, coordinates: null, confidence: 0, source: "booking_autocomplete" }; return normalizeBookingLocationResponse(result.payload, query); }, async searchHotels(input) { if (input.exactPropertyRequest) { const match = await this.resolveProperty(input); if (match.status === "AMBIGUOUS") return unavailable("EXACT_PROPERTY_AMBIGUOUS", "The requested hotel property matched multiple Booking.com properties."); if (!match.providerPropertyId) return unavailable("EXACT_PROPERTY_NOT_FOUND", "The requested hotel property was not found."); return search(input, [match.providerPropertyId], true); } return search(input); }, async resolveProperty(input) { if (!input.exactPropertyRequest || !input.bookerCountry) return { status: "NOT_FOUND", providerPropertyId: null, canonicalName: null, confidence: 0, candidates: [] }; const result = await raw("/common/autocomplete", { query: input.exactPropertyRequest, country: input.bookerCountry.toLowerCase(), filters: { types: ["hotel"] } }); if (result.state !== "OK") return { status: "NOT_FOUND", providerPropertyId: null, canonicalName: null, confidence: 0, candidates: [] }; const parsed = propertyRows(result.payload); return resolveBookingPropertyMatch(input.exactPropertyRequest, parsed?.rows || []); }, getPropertyAvailability: input => search(input, [input.providerPropertyId], true), getRates: input => search(input, [input.providerPropertyId], true) };
}
export function providerStatusForCandidate(candidate: HotelCandidate) { return candidate.sourceType === "provider_api" && candidate.factualStatus === "verified" && candidate.availabilityStatus === "available" ? "VERIFIED_INVENTORY" : "DISCOVERY_ONLY"; }
