import Link from "next/link";
import { Button } from "@/components/ui/Button";
import { DynamicDestinationHero } from "@/components/roamly/DynamicDestinationHero";
import { CityPuzzle } from "@/components/roamly/CityPuzzle";

export default function Home() {
  return (
    <main className="safe-bottom overflow-hidden bg-[#f7f7ee] text-ink">
      <DynamicDestinationHero />
      <CityPuzzle />

      <section id="the-journey" className="roamly-enter mx-auto w-full max-w-7xl px-5 py-10 sm:px-8 sm:py-14 lg:px-12" style={{ animationDelay: "80ms" }}>
        <div className="grid gap-8 lg:grid-cols-[0.7fr_1.3fr] lg:items-center lg:gap-16">
          <div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#167b86]">The planning moment</p><h2 className="mt-3 max-w-md text-3xl font-bold leading-[1] tracking-[-0.04em] text-ink sm:text-4xl">From a feeling to a day you can follow.</h2><p className="mt-4 max-w-sm text-sm leading-6 text-slate-600">Roamly keeps the big picture and the next decision together.</p></div>
          <div className="relative py-1 sm:pl-4"><div className="flex items-start justify-between gap-4 border-b border-[#d8e5dd] pb-4"><div><p className="text-[0.65rem] font-bold uppercase tracking-[0.16em] text-[#167b86]">A considered day · 02</p><h3 className="mt-1 text-xl font-bold tracking-tight text-ink sm:text-2xl">Room to wander</h3></div><span className="shrink-0 text-sm font-bold text-[#167b86]">Barcelona</span></div>
            <div className="relative mt-4 border-l-2 border-[#b8ded4] pl-5 sm:pl-6">
              {[['Morning','Gothic Quarter','walk + coffee','4fd1bd'],['Afternoon','One good plan','nearby, with room','f6bd68'],['Evening','Choose your pace','free to choose','ef866f']].map(([time,title,detail,color], index) => <div key={time}><div className="relative grid grid-cols-[4.5rem_1fr] items-center gap-3 py-2"><span aria-hidden="true" className="absolute -left-[1.85rem] grid h-4 w-4 place-items-center rounded-full ring-4 ring-[#f4efe5]" style={{ backgroundColor: `#${color}` }} /><span className="text-xs font-bold text-slate-500">{time}</span><div className={index < 2 ? "border-b border-[#d8e5dd] pb-2" : "pb-2"}><p className="text-sm font-bold text-ink">{title}</p><p className="mt-0.5 text-xs text-slate-500">{detail}</p></div></div>{index < 2 && <p className="py-1 text-[0.68rem] font-bold text-[#167b86]">↓ {index === 0 ? "nearby" : "room left intentionally"}</p>}</div>)}
            </div>
            <p className="mt-4 border-t border-[#d8e5dd] pt-3 text-[0.68rem] font-bold text-slate-500">Budget still in view</p>
          </div>
        </div>
      </section>

      <section className="roamly-enter bg-[#eaf5ef] px-5 py-14 text-[#203c43] sm:px-8 sm:py-20 lg:px-12" style={{ animationDelay: "140ms" }}><div className="mx-auto grid w-full max-w-7xl gap-8 lg:grid-cols-[1fr_0.8fr] lg:items-center lg:gap-16"><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#16877f]">When the trip becomes real</p><h2 className="mt-3 max-w-xl text-3xl font-bold leading-[1] tracking-[-0.04em] sm:text-4xl">Roamly comes with you.</h2><p className="mt-4 max-w-md text-sm leading-6 text-[#526b6c]">Keep the next useful thing close while you are already on the move.</p></div><div className="rounded-[1.5rem] border border-[#cfe5d8] bg-white/90 p-5 shadow-[0_18px_50px_rgba(39,88,80,0.09)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_24px_60px_rgba(39,88,80,0.13)] motion-reduce:transform-none motion-reduce:transition-none sm:p-7"><div className="flex items-center justify-between gap-3"><p className="text-[0.65rem] font-extrabold uppercase tracking-[0.16em] text-[#16877f]">Live Companion · premium</p><span className="rounded-full bg-[#e6f6ed] px-3 py-1 text-xs font-bold text-[#347b62]">Your trip, in the moment</span></div><div className="mt-5 rounded-2xl bg-[#f4f8ef] p-4"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-[#71877d]">Now</p><p className="mt-1 text-xl font-bold text-[#203c43]">Dinner in the old quarter</p></div><div className="mt-3 flex items-center gap-3 rounded-2xl border border-[#e4eee5] bg-white p-4"><span aria-hidden="true" className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#fff0dc] text-[#a65d32]">→</span><div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-[#71877d]">Whenever you’re ready</p><p className="mt-1 text-base font-bold text-[#49655d]">An evening left open</p></div></div></div></div></section>

      <section className="roamly-enter bg-[#dff2e8] px-5 py-12 text-[#203c43] sm:px-8 sm:py-16 lg:px-12" style={{ animationDelay: "200ms" }}><div className="mx-auto flex w-full max-w-7xl flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#167b78]">Your next somewhere</p><h2 className="mt-2 max-w-xl text-3xl font-bold leading-[1] tracking-[-0.04em] sm:text-4xl">Make room for a trip that feels like yours.</h2></div><div className="shrink-0"><div className="flex flex-wrap items-center gap-3"><Button href="/plan" className="min-h-12 rounded-full bg-[#16877f] px-6 text-white shadow-sm transition duration-200 hover:-translate-y-0.5 hover:bg-[#11756e] motion-reduce:transform-none motion-reduce:transition-none">Start planning</Button><Link href="/pricing" className="rounded-full border border-[#b8d6ca] bg-white/90 px-5 py-3 text-sm font-bold text-[#28665d] transition duration-200 hover:-translate-y-0.5 hover:border-[#78bba8] hover:bg-white motion-reduce:transform-none motion-reduce:transition-none">See pricing</Link></div><p className="mt-2 text-xs font-semibold text-[#42655d]">One full itinerary included per account, for life.</p></div></div></section>
      <footer className="border-t border-[#e0e8dc] bg-[#fffdf7] px-5 py-8 text-[#526b6c] sm:px-8 lg:px-12"><div className="mx-auto flex w-full max-w-7xl flex-col gap-4 text-sm sm:flex-row sm:items-center sm:justify-between"><p className="font-semibold text-[#49655d]">Roamly — travel planning that stays with the trip.</p><div className="flex flex-wrap gap-5 font-semibold text-[#647c76]"><Link href="/pricing" className="transition-colors hover:text-[#16877f]">Pricing</Link><Link href="/terms" className="transition-colors hover:text-[#16877f]">Terms</Link><Link href="/privacy" className="transition-colors hover:text-[#16877f]">Privacy</Link><Link href="/contact" className="transition-colors hover:text-[#16877f]">Contact</Link></div></div></footer>
    </main>
  );
}
