import { NextRequest, NextResponse } from "next/server";
import { buildPreviewFromItinerary } from "@/lib/itinerary";
import { isEmailConfigured, sendRoamlyEmail } from "@/lib/roamly/email";
import { requireUser } from "@/lib/roamly/auth";
import { getTripDestinationLabel } from "@/lib/roamly/tripMetadata";
import { getTripBundle, isMissingTableError } from "@/lib/trips";

function getString(value: unknown) {
  return typeof value === "string" ? value.trim() : "";
}

function escapeHtml(value?: string | null) {
  return (value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function plainDaySummary(days: Array<{ day_number: number; city?: string; title: string; morning: string; afternoon: string; evening: string }>) {
  return days
    .map((day) =>
      [
        `Day ${day.day_number}${day.city ? ` - ${day.city}` : ""}: ${day.title}`,
        `Morning: ${day.morning}`,
        `Afternoon: ${day.afternoon}`,
        `Evening: ${day.evening}`
      ].join("\n")
    )
    .join("\n\n");
}

function renderItineraryEmail({
  title,
  destination,
  dates,
  summary,
  days,
  tripUrl
}: {
  title: string;
  destination: string;
  dates: string;
  summary: string;
  days: Array<{ day_number: number; city?: string; title: string; morning: string; afternoon: string; evening: string }>;
  tripUrl: string;
}) {
  const dayHtml = days
    .slice(0, 10)
    .map(
      (day) => `<section style="border-top:1px solid #e5edf3;padding:16px 0;">
        <p style="margin:0 0 6px;font-size:12px;font-weight:900;letter-spacing:.14em;text-transform:uppercase;color:#0f8f9c;">Day ${day.day_number}${day.city ? ` - ${escapeHtml(day.city)}` : ""}</p>
        <h2 style="margin:0 0 10px;font-size:18px;line-height:1.25;color:#132033;">${escapeHtml(day.title)}</h2>
        <p style="margin:0 0 6px;font-size:14px;line-height:1.6;color:#526176;"><strong>Morning:</strong> ${escapeHtml(day.morning)}</p>
        <p style="margin:0 0 6px;font-size:14px;line-height:1.6;color:#526176;"><strong>Afternoon:</strong> ${escapeHtml(day.afternoon)}</p>
        <p style="margin:0;font-size:14px;line-height:1.6;color:#526176;"><strong>Evening:</strong> ${escapeHtml(day.evening)}</p>
      </section>`
    )
    .join("");

  const html = `<!doctype html>
<html>
  <body style="margin:0;background:#f7fcff;font-family:Arial,sans-serif;color:#132033;">
    <main style="max-width:680px;margin:0 auto;padding:24px;">
      <section style="background:#ffffff;border:1px solid #dce8f2;border-radius:24px;padding:28px;box-shadow:0 18px 45px rgba(31,45,61,0.10);">
        <p style="margin:0 0 14px;font-size:12px;font-weight:900;letter-spacing:.18em;text-transform:uppercase;color:#0aa6a6;">Roamly itinerary</p>
        <h1 style="margin:0;font-size:30px;line-height:1.08;color:#132033;">${escapeHtml(title)}</h1>
        <p style="margin:12px 0 0;font-size:15px;font-weight:700;color:#526176;">${escapeHtml(destination)}${dates ? ` · ${escapeHtml(dates)}` : ""}</p>
        <p style="margin:18px 0 0;font-size:15px;line-height:1.65;color:#526176;">${escapeHtml(summary)}</p>
        <a href="${escapeHtml(tripUrl)}" style="display:inline-block;margin-top:20px;background:#0f8f9c;color:#ffffff;text-decoration:none;border-radius:999px;padding:13px 18px;font-weight:900;">Open trip in Roamly</a>
      </section>
      <section style="background:#ffffff;border:1px solid #dce8f2;border-radius:24px;padding:24px;margin-top:18px;">
        ${dayHtml}
      </section>
      <p style="margin:18px 8px 0;font-size:12px;line-height:1.6;color:#7a8798;">PDF export is available from the trip page. Generated by Roamly.</p>
    </main>
  </body>
</html>`;

  const text = `${title}\n${destination}${dates ? ` - ${dates}` : ""}\n\n${summary}\n\n${plainDaySummary(days)}\n\nOpen trip: ${tripUrl}\nPDF export is available from the trip page.\n\nGenerated by Roamly.`;
  return { html, text };
}

function formatDateRange(start?: string | null, end?: string | null) {
  if (!start && !end) return "";
  return [start, end].filter(Boolean).join(" to ");
}

export async function POST(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const auth = await requireUser();
  if (!auth.ok) return auth.response;

  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;
  const to = getString(body.to);
  if (!to) {
    return NextResponse.json({ ok: false, error: "Recipient email is required." }, { status: 400 });
  }

  const bundleResult = await getTripBundle(auth.supabase, auth.user.id, id);
  if (!bundleResult.data) {
    if (isMissingTableError(bundleResult.error)) {
      return NextResponse.json({ ok: false, error: "Trip tables are not ready." }, { status: 503 });
    }
    return NextResponse.json({ ok: false, error: "Trip not found." }, { status: 404 });
  }

  const config = isEmailConfigured();
  if (!config.configured) {
    return NextResponse.json(
      {
        ok: false,
        result: { status: "skipped" },
        message: "Email sending is not configured yet. You can export the PDF or copy the trip link."
      },
      { status: 202 }
    );
  }

  const { trip, itinerary } = bundleResult.data;
  const full = itinerary?.full_json;
  if (!full) {
    return NextResponse.json({ ok: false, error: "Generate and lock this itinerary before emailing it." }, { status: 400 });
  }

  const preview = buildPreviewFromItinerary(full);
  const title = trip.title || preview.trip_title || full.trip_title;
  const destination = getTripDestinationLabel(trip) || full.destination_summary || "Your trip";
  const dates = formatDateRange(trip.start_date, trip.end_date);
  const tripUrl = `${request.nextUrl.origin}/trip/${id}`;
  const rendered = renderItineraryEmail({
    title,
    destination,
    dates,
    summary: full.destination_summary,
    days: full.daily_itinerary,
    tripUrl
  });

  const result = await sendRoamlyEmail({
    to,
    subject: `Roamly itinerary: ${title}`,
    html: rendered.html,
    text: rendered.text,
    userId: auth.user.id,
    tripId: id,
    metadata: { type: "trip_itinerary_share", source: "trip_page" }
  });

  const message =
    result.status === "skipped"
      ? "Email sending is not configured yet. You can export the PDF or copy the trip link."
      : result.ok
        ? "Itinerary email sent."
        : result.error || "Could not send itinerary email.";

  return NextResponse.json({ ok: result.ok, result, message }, { status: result.ok ? 200 : result.status === "skipped" ? 202 : 400 });
}
