"use client";

import { useState } from "react";

type Props = { tripId: string; startDate: string | null; endDate: string | null; status: string };
type Proposal = { id: string; requested_start_date: string; requested_end_date: string; result: { note?: string; refreshes?: string[] } };

export default function CustomerDateChange({ tripId, startDate, endDate, status }: Props) {
  const [open, setOpen] = useState(false); const [start, setStart] = useState(startDate || ""); const [end, setEnd] = useState(endDate || ""); const [proposal, setProposal] = useState<Proposal | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  if (!["generated", "locked", "planned"].includes(status)) return null;
  async function preview() { setBusy(true); setMessage(""); try { const response = await fetch(`/api/trips/${tripId}/date-change`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ startDate: start, endDate: end }) }); const body = await response.json(); if (!response.ok || !body.proposal) throw new Error(body.message || body.error || "Date preview unavailable."); setProposal(body.proposal); } catch (error) { setMessage(error instanceof Error ? error.message : "Date preview unavailable."); } finally { setBusy(false); } }
  async function apply() { if (!proposal) return; setBusy(true); setMessage(""); try { const response = await fetch(`/api/trips/${tripId}/date-change/${proposal.id}/apply`, { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Date change could not be started."); window.location.href = `/trip/${body.successorTripId}?generating=1`; } catch (error) { setMessage(error instanceof Error ? error.message : "Date change could not be started."); } finally { setBusy(false); } }
  return <div className="roamly-no-print mt-4">{!open ? <button type="button" onClick={() => setOpen(true)} className="min-h-10 rounded-full border border-ocean/30 px-4 py-2 text-xs font-black text-ocean hover:bg-ocean/5">Change dates</button> : <div className="max-w-xl rounded-xl border border-[#e8dfd0] bg-[#fffdf8] px-4 py-4"><p className="font-black text-ink">Change your trip dates</p>{!proposal ? <><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-black uppercase tracking-[0.12em] text-slate-500">Start<input type="date" value={start} onChange={(e) => setStart(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-base font-bold text-ink" /></label><label className="text-xs font-black uppercase tracking-[0.12em] text-slate-500">End<input type="date" value={end} onChange={(e) => setEnd(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-base font-bold text-ink" /></label></div><button type="button" onClick={preview} disabled={busy} className="mt-3 min-h-10 rounded-full bg-ocean px-4 py-2 text-xs font-black text-white disabled:opacity-60">{busy ? "Checking…" : "Preview change"}</button></> : <><p className="mt-2 text-sm font-bold text-slate-700">New dates: {proposal.requested_start_date} to {proposal.requested_end_date}</p><p className="mt-2 text-sm font-semibold text-slate-600">Your existing bookings will not be changed. Flights, hotels, activities, events, prices, and routing will be refreshed for the new dates.</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={apply} disabled={busy} className="min-h-10 rounded-full bg-ocean px-4 py-2 text-xs font-black text-white disabled:opacity-60">{busy ? "Starting…" : "Create new itinerary"}</button><button type="button" onClick={() => setProposal(null)} disabled={busy} className="min-h-10 rounded-full border border-slate-300 px-4 py-2 text-xs font-black text-slate-700">Review again</button></div></>}{message ? <p className="mt-2 text-xs font-bold text-amber-800" aria-live="polite">{message}</p> : null}<button type="button" onClick={() => { setOpen(false); setProposal(null); }} className="mt-3 text-xs font-black text-slate-500 underline">Cancel</button></div>}</div>;
}
